### ISSUE TITLE
Referenced logo is outdated

### ISSUE THREAD

**Issue by todrobbins** [datproject/newsletter#4] opened 2019-04-17 22:49 UTC
Referenced logo is outdated, but an issue has been created at datproject/design/issues/31

_Originally posted by @todrobbins in https://github.com/datproject/newsletter/pull/3#issuecomment-484289941_

**Comment by todrobbins** [comment] 2019-05-01 22:09
@joehand any update on this before the first newsletter goes out?

**Comment by joehand** [comment] 2019-05-03 15:58
what do I need to do to close this issue? Sorry wasn't ignoring this just wasn't sure what the ask is =). Shoulda said something!

**Comment by RangerMauve** [comment] 2019-05-03 22:15
Oh, I think we need an SVG (or a png, I guess) to the new logo for the newsletter.

**Comment by RangerMauve** [comment] 2019-05-03 22:49
Err, actually. Is it out of date? :S It seems like the logo referenced in the issue is the same as the one in the newsletter.

**Comment by todrobbins** [comment] 2019-05-09 03:18
The Dat logo in the current newsletter template is this one: 

![](https://datproject.github.io/design/downloads/dat-data-logo.svg)
https://datproject.github.io/design/downloads/dat-data-logo.svg

Is the current Dat logo this one?

![](https://user-images.githubusercontent.com/684965/56325596-9d2b7300-6127-11e9-9b10-ac6360538114.png)

**Comment by joehand** [comment] 2019-05-09 15:18
Yes, logos are https://datproject.org/public/img/dat-logo.png for 32px+ uses and https://datproject.org/public/img/dat-logo-small.png for smaller uses. I dont have svg but could convert (?) or remake them.

**Comment by todrobbins** [comment] 2019-05-14 15:07
Sorry for the confusion! I just got back from vacation and will update the reference to `dat-logo.png`

**Comment by todrobbins** [comment] 2019-05-14 15:13
Fixed with 523fafa67522bee53070f554f8bf292df54d8af2

**Closed** 2019-05-14 15:13 UTC

**Comment by RangerMauve** [comment] 2019-05-14 19:26
You Da Bomb! 💣💣💣💣💣
